# Generated by Django 4.2.3 on 2023-07-12 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activa', models.BooleanField(default=True)),
                ('fecha_nacimiento', models.DateField(max_length=30)),
                ('direccion', models.CharField(max_length=30)),
                ('creado_el', models.DateField()),
                ('actualizado_el', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cuentas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activa', models.BooleanField(default=True)),
                ('saldo', models.IntegerField(blank=True, null=True)),
                ('creado_el', models.DateField(blank=True, null=True)),
                ('actualizado_el', models.DateTimeField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banc.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, null=True)),
                ('apellido', models.CharField(max_length=50, null=True)),
                ('cedula', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TiposCuentas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_cuenta', models.CharField(blank=True, choices=[('AHORRO', 'AHORRO'), ('CORRIENTE', 'CORRIENTE')], default='AHORRO', max_length=50, null=True)),
                ('descripcion', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Movimientos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimiento', models.CharField(choices=[('DEPOSITO', 'DEPOSITO'), ('RETIRO', 'RETIRO'), ('TRANSFERENCIA', 'TRANSFERENCIA'), ('PAGO', 'PAGO'), ('INTERESES', 'INTERESES'), ('AJUSTES', 'AJUSTES')], max_length=50)),
                ('monto', models.IntegerField()),
                ('actualizado_el', models.DateField()),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banc.cuentas')),
            ],
        ),
        migrations.AddField(
            model_name='cuentas',
            name='tipo_cuenta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banc.tiposcuentas'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banc.persona'),
        ),
    ]
